export const projects = [
  {
    title: 'Scramble game',
    description: "A simple word scramble game to guess the words within the time limit using the hint provided and options to skip the word.",
    image: '/images/2.png',
    tags: ['HTML', 'CSS', 'Javascript'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 0,
  },
  {
    title: 'MarkDown Editor',
    description: "A Markdown editor using React and Bootstrap that seamlessly blends simplicity with style for enhanced document creation.",
    image: '/images/4.jpg',
    tags: ['React', 'BootStrap'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 1,
  },
  {
    title: 'Motion Alarm',
    description: "I've created a small intresting project that uses Telegram Chat Bot, Python Open CV, and a simple camera setup to detect motion in front of the camera to trigger alarm sound and sends a Telegram notification when 5 consecutive alarm bells are triggered. It helps us to understand how hardware interacts with software.",
    // description: "Using React, Node.js, Express & MongoDB you'll learn how to build a Full Stack MERN Application - from start to finish. The App is called Memories and it is a simple social media app that allows users to post interesting events that happened in their lives.",
    image: '/images/1.png',
    tags: ['Python', 'Open CV'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: 'Sorting Visualizer',
    description: "I have made this Sorting Visualizer, a dynamic web application built with React. User can Witness the magic of Bubble, Selection, Insertion, Merge, Quick, and Heap sorts in real time action with adjustable speed and size controls or the blocks of data, gaining insights into algorithmic efficiency and complexity in real-time.",
    image: '/images/3.png',
    tags: ['React', 'WebRTC'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },
  {
    title: 'Sibling Chat',
    description: "This is a code repository for the corresponding YouTube video. In this tutorial, we're going to build and deploy a React Video Chat Application using WebRTC.",
    image: '/images/4.jpg',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 4,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Completed My 10th', },
  { year: 2019, text: 'Completed My 12th', },
  { year: 2020, text: 'Started my college Journey', },
  { year: 2021, text: 'Started my DSA Journey and Youtube Channel', },
  { year: 2022, text: 'Got Intern for 2 months as a web Developer', },
  { year: 2023, text: 'Continuing my development Journey', },
];